### ISSUE TITLE
Possible bug with overpreassure on stock pipe/bridge

### ISSUE THREAD

**Issue by mrstoned-gh** [SuperCorgi/ONI-Mods#4]
Attaching screenshots and output logs
[output_log.txt](https://github.com/SuperCorgi/ONI-Mods/files/5052935/output_log.txt)
![20200810142101_1](https://user-images.githubusercontent.com/40145223/89823129-3cf8e580-db51-11ea-92b4-6798fe8d54ce.jpg)
![20200810142052_1](https://user-images.githubusercontent.com/40145223/89823136-41bd9980-db51-11ea-9924-cb261a56d896.jpg)

I have one mod that may interfere, Longer Bridges, and going to redraw some pipes and try without it as well.

**Comment by SuperCorgi** [comment]
Issue closed, appears to have been an outdated version of the mod being served by Steam.
